# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: MyExperiments
email: abrunet01@gmail.com
description: "A blog about IT Security experiments"
keywords: "it,security,blog,cyber,experiments,it security blog,it blog"

url: "https://myexperiments.io"

twitter_url: L0vvebug
github_url:  L0v3bug
linkedin_url: antoine-brunet-44b3bb13b

# Build settings
markdown: kramdown
safe: true
encoding: utf-8
timezone: America/New_York
